### PR TITLE
updated code check created feature

### PR DESCRIPTION
**Pull request by nomanqaiser**
amazing

### CODE REVIEW

**Review by RegalCoderz — COMMENTED** [review]
have you created the new branch named as "feature" and then created the pull request"?

**Comment by RegalCoderz** [comment]
> 
@nomanqaiser

**Comment by nomanqaiser** [comment]
> have you created the new branch named as "feature" and then created the pull request"?

ok noted

**Comment by RegalCoderz** [comment]
o pai

**Comment by RegalCoderz** [comment]
hello

**Comment by nomanqaiser** [comment]
ok as u wish

**Comment by RegalCoderz** [comment]
hello

**Comment by RegalCoderz** [comment]
hello @nomanqaiser

**Comment by RegalCoderz** [comment]
check now

**Comment by RegalCoderz** [comment]
check again
@nomanqaiser

**Comment by nomanqaiser** [comment]
okl

**Comment by RegalCoderz** [comment]
check

**Comment by RegalCoderz** [comment]
> okl

dgdfgdfh

**Comment by RegalCoderz** [comment]
hhh

**Comment by RegalCoderz** [comment]
from vs code

**Comment by RegalCoderz** [comment]
efjhferhakf

**Pull request merged**
